# Generated by Django 4.1.7 on 2023-03-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Товары', 'verbose_name_plural': 'Товары'},
        ),
    ]
